#!/usr/bin/env python3
"""stage_redo.py — REDO one pre-production stage without losing the last version and without cascading.

A redo is the normal case (a note on the shot list, one shot's prompt rewritten), and two things go wrong in it silently:
the version the operator last approved is overwritten, and a redo of one stage quietly re-runs the stages after it — work
nobody asked for, billed or not. So a redo here:
  1  copies the current file to <its dir>/versions/<stem>.v<N>.<YYYYMMDD-HHMMSS><ext> (N = the versions already kept + 1;
     every version kept, none deleted)
  2  appends ONE metadata row to <root>/receipts/stage-runlog.md — time, stage, action, file, backup — never the file's text
  3  names the downstream stages whose files may now be STALE, in the house order, and stops: it never cascades — the
     operator decides which downstream stage is redone (each one a redo of its own, through this script)
Then the stage is regenerated by whoever owns it. `log` records a first generation (no backup). Pattern: feicaiclub's
script-breakdown (the versions folder, the metadata-only run log, "it never cascades on its own").

The stage order: script → beats → shotlist → refs → prompts → takes → edl → mix → finish. Stage isolation is the other half
(video-production PREPRODUCTION-CORE.md § 7): each stage reads ONLY its upstream files — the prompt stage reads the shot list
and the reference set, never the script — so a stale upstream shows as a named stage here, not as drift inside a prompt.

  stage_redo.py redo --root <project> --stage <stage> <file>…    # back up, log, name what may be stale
  stage_redo.py log  --root <project> --stage <stage> <file>…    # a first generation: log only
  stage_redo.py --selftest
"""
import argparse, glob, os, shutil, sys, tempfile, time

ORDER = ['script', 'beats', 'shotlist', 'refs', 'prompts', 'takes', 'edl', 'mix', 'finish']
LOG = os.path.join('receipts', 'stage-runlog.md')


def row(root, stage, action, f, backup):
    p = os.path.join(root, LOG); os.makedirs(os.path.dirname(p), exist_ok=True); new = not os.path.exists(p)
    with open(p, 'a') as h:
        if new: h.write('| time | stage | action | file | backup |\n|---|---|---|---|---|\n')
        h.write(f"| {time.strftime('%Y-%m-%dT%H:%M:%S')} | {stage} | {action} | {f} | {backup or '—'} |\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('cmd', nargs='?', choices=['redo', 'log']); ap.add_argument('files', nargs='*')
    ap.add_argument('--root', default='.'); ap.add_argument('--stage', choices=ORDER); ap.add_argument('--selftest', action='store_true')
    a = ap.parse_args(argv)
    if a.selftest: return selftest()
    if not (a.cmd and a.stage and a.files): ap.error('redo|log --stage <stage> <file>…')
    root = a.root
    for f in a.files:
        fp = f if os.path.isabs(f) else os.path.join(root, f)
        if not os.path.isfile(fp): print(f'STAGE-REFUSED {f}: no such file — a redo backs up what exists'); return 3
        if a.cmd == 'log': row(root, a.stage, 'first', os.path.relpath(fp, root), None); print(f'STAGE-LOGGED {a.stage} {f}'); continue
        d, base = os.path.split(fp); stem, ext = os.path.splitext(base); vd = os.path.join(d, 'versions'); os.makedirs(vd, exist_ok=True)
        n = len(glob.glob(os.path.join(vd, f'{glob.escape(stem)}.v*{glob.escape(ext)}'))) + 1
        bk = os.path.join(vd, f"{stem}.v{n}.{time.strftime('%Y%m%d-%H%M%S')}{ext}")
        if os.path.exists(bk): print(f'STAGE-REFUSED {bk} exists'); return 3
        shutil.copy2(fp, bk); row(root, a.stage, 'redo', os.path.relpath(fp, root), os.path.relpath(bk, root))
        print(f'STAGE-BACKED-UP {f} → {os.path.relpath(bk, root)} (v{n}; every version kept)')
    down = ORDER[ORDER.index(a.stage) + 1:]
    if a.cmd == 'redo' and down:
        print(f"MAY BE STALE after a {a.stage} redo: {' → '.join(down)} — NOT redone: the operator decides which, each a redo of its own")
    return 0


def selftest():
    with tempfile.TemporaryDirectory() as r:
        os.makedirs(os.path.join(r, 'prompts', 'r2v')); f = os.path.join(r, 'prompts', 'r2v', 'SPOT-SHOTLIST.md'); open(f, 'w').write('v1 text')
        q = lambda *x: main(['--root', r, *x])
        chk = [('a redo of a missing file is refused', q('redo', '--stage', 'shotlist', 'prompts/r2v/NOPE.md') == 3),
               ('log records a first generation', q('log', '--stage', 'shotlist', 'prompts/r2v/SPOT-SHOTLIST.md') == 0)]
        chk.append(('redo backs up v1 and keeps the file', q('redo', '--stage', 'shotlist', 'prompts/r2v/SPOT-SHOTLIST.md') == 0 and os.path.exists(f)))
        open(f, 'w').write('v2 text'); time.sleep(1.1)
        chk.append(('a second redo keeps both versions', q('redo', '--stage', 'shotlist', 'prompts/r2v/SPOT-SHOTLIST.md') == 0
                    and sorted(open(p).read() for p in glob.glob(os.path.join(r, 'prompts', 'r2v', 'versions', '*'))) == ['v1 text', 'v2 text']))
        log = open(os.path.join(r, LOG)).read()
        chk.append(('the run log holds metadata only, never the text', log.count('\n') == 5 and 'v1 text' not in log and 'v2 text' not in log))
    for name, ok in chk: print(f"{'ok  ' if ok else 'FAIL'} {name}")
    ok = all(v for _, v in chk); print(f"SELFTEST {'PASS' if ok else 'FAIL'} ({sum(v for _, v in chk)}/{len(chk)})"); return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
